# Generated by Django 5.2.4 on 2025-07-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_otp_user_otp_expired'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserId',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='googleId',
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
    ]
