# Generated by Django 5.2.4 on 2025-07-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_options_rename_userid_user_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
