# Generated by Django 5.2.4 on 2025-07-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='videos_progress',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
