# Generated by Django 5.2.4 on 2025-07-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_videos_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('german', 'German')], default='english', max_length=20),
        ),
    ]
