# Generated by Django 5.2.4 on 2025-07-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='subtitle_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
