# Generated by Django 5.2.4 on 2025-07-21 11:15

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='category_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='videos/'),
        ),
    ]
