# Generated by Django 5.2.4 on 2025-08-11 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_course_videolesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_videos', to='tutorials.course'),
        ),
    ]
