# Generated by Django 5.2.4 on 2025-07-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_videolesson_subtitle_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolesson',
            name='video_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
