# Generated by Django 5.2.4 on 2025-07-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_alter_videolesson_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolesson',
            name='video_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='video_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
