# Generated by Django 5.2.4 on 2025-07-30 04:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_alter_videolesson_video_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolesson',
            name='video_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
