# Generated by Django 5.2.4 on 2025-07-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_liveclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
