# Generated by Django 5.2.4 on 2025-07-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_alter_videolesson_video_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolesson',
            name='video_path',
            field=models.CharField(blank=True, max_length=955, null=True),
        ),
    ]
