# Generated by Django 5.2.4 on 2025-07-26 06:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalChatSession',
            fields=[
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='New Session', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalPDF',
            fields=[
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_id', models.CharField(max_length=16, unique=True)),
                ('pdf_filename', models.CharField(max_length=255)),
                ('pdf_path', models.FilePathField(path='global_pdfs')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_id', models.CharField(max_length=16, unique=True)),
                ('video_filename', models.CharField(max_length=255)),
                ('video_path', models.FilePathField(path='videos')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalMessage',
            fields=[
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.globalchatsession')),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_object_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('video_filename', models.CharField(max_length=255)),
                ('pdf_filename', models.CharField(max_length=255)),
                ('transcript', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.video')),
            ],
        ),
    ]
