# Generated by Django 5.2.4 on 2025-07-27 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_video_file_alter_video_video_filename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitle',
            name='video_id',
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='video_object_id',
        ),
        migrations.AddField(
            model_name='subtitle',
            name='video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='ai.video'),
            preserve_default=False,
        ),
    ]
