# Generated by Django 5.2.4 on 2025-07-30 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_globalchatsession_user'),
        ('tutorials', '0007_alter_videolesson_video_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='tutorials.videolesson'),
        ),
    ]
